name: navix
description: "An AI university student guide."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  form_field_validator: ^1.1.0
  fluttertoast: ^8.2.8
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.4.0
  syncfusion_flutter_calendar: ^27.1.48
  page_transition: ^2.1.0
  shared_preferences: ^2.3.2
  loading_indicator: ^3.1.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.1
  provider: ^6.1.2
  flutter_gemini: ^2.0.5
  flutter_dotenv: ^5.1.0
  youtube_player_flutter: ^9.1.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  home_widget: ^0.7.0
  random_color: ^1.0.5
  cron: ^0.6.1
  percent_indicator: ^4.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/jsons/

