class SuggestionsLists {
  List<String> prefSuggestions = [
    'Designing',
    'Coding',
    'Testing',
    'UI/UX',
    'Machine Learning',
    'Web Development',
    'Mobile App Development',
    'Data Science',
    'Artificial Intelligence',
    'Blockchain',
    'Cybersecurity',
    'Cloud Computing',
    'Database Management',
    'Project Management',
    'Agile Methodologies',
    'DevOps',
    'Software Engineering',
    'Graphic Design',
    'Front-end Development',
    'Back-end Development',
    'Full-stack Development',
    'React',
    'Vue.js',
    'Angular',
    'Flutter',
    'Dart Programming',
    'Python Programming',
    'Java Programming',
    'JavaScript Programming',
    'Node.js',
    'PHP',
    'Ruby',
    'C++ Programming',
    'C# Programming',
    'Swift',
    'Kotlin',
    'Android Development',
    'iOS Development',
    'Digital Marketing',
    'SEO Optimization',
    'Social Media Management',
    'Content Writing',
    'Copywriting',
    'Business Analysis',
    'System Architecture',
    'Cloud Architecture',
    'Machine Vision',
    'Data Visualization',
    'Data Engineering',
    'Natural Language Processing',
    'Deep Learning',
    'Computer Vision',
    'Game Development',
    'Unity',
    'Unreal Engine',
    '3D Modeling',
    'Animation',
    'Augmented Reality',
    'Virtual Reality',
    'Internet of Things (IoT)',
    'Edge Computing',
    'Quantum Computing',
    'Robotics',
    'Automation Testing',
    'Manual Testing',
    'Selenium',
    'Test Automation Frameworks',
    'CI/CD',
    'Test Driven Development',
    'Unit Testing',
    'Integration Testing',
    'System Testing',
    'Acceptance Testing',
    'Product Management',
    'UI Design',
    'UX Design',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Interaction Design',
    'Branding',
    'Typography',
    'Color Theory',
    'Sketch',
    'Figma',
    'Adobe Photoshop',
    'Adobe Illustrator',
    'Adobe XD',
    'InVision',
    'Zeplin',
    'Marketing Automation',
    'Email Marketing',
    'Customer Relationship Management',
    'Salesforce',
    'HubSpot',
    'Shopify Development',
    'Magento Development',
    'WooCommerce Development',
    'E-commerce Development',
    'SEO Tools',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'Content Strategy',
    'SEO Copywriting',
    'User Interface',
    'User Experience',
    'Front-end Frameworks',
    'CSS Preprocessors',
    'SCSS',
    'SASS',
    'LESS',
    'Responsive Design',
    'Progressive Web Apps',
    'Microservices',
    'API Development',
    'RESTful API',
    'GraphQL',
    'OAuth',
    'JWT Authentication',
    'Web Accessibility',
    'Cross-platform Development',
    'App Store Optimization',
    'App Development Frameworks',
    'Test Automation Tools',
    'App Design',
    'Database Design',
    'NoSQL Databases',
    'SQL Databases',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Firebase',
    'SQLite',
    'Hadoop',
    'Spark',
    'Machine Learning Algorithms',
    'Artificial Intelligence Models',
    'Neural Networks',
    'Reinforcement Learning',
    'Supervised Learning',
    'Unsupervised Learning',
    'Generative Adversarial Networks',
    'Bayesian Networks',
    'Support Vector Machines',
    'Random Forests',
    'K-means Clustering',
    'Principal Component Analysis',
    'Dimensionality Reduction',
    'Anomaly Detection',
    'Text Mining',
    'Speech Recognition',
    'Face Recognition',
    'Sentiment Analysis',
    'Chatbots',
    'NLP Pipelines',
    'Time Series Forecasting',
    'Predictive Analytics',
    'Business Intelligence',
    'Data Mining',
    'Big Data Analytics',
    'ETL Processes',
    'Data Warehousing',
    'Data Lakes',
    'Data Quality',
    'Data Governance',
    'Data Privacy',
    'Data Security',
    'Data Integration',
    'Cloud Storage',
    'SaaS Solutions',
    'PaaS Solutions',
    'IaaS Solutions',
    'Private Cloud',
    'Public Cloud',
    'Hybrid Cloud',
    'Serverless Architecture',
    'Cloud Migration',
    'Infrastructure as Code',
    'Containers',
    'Docker',
    'Kubernetes',
    'Serverless Framework',
    'AWS Lambda',
    'Azure Functions',
    'Google Cloud Functions',
    'Terraform',
    'Ansible',
    'Chef',
    'Puppet',
    'OpenStack',
    'Microservices Architecture',
    'API Gateway',
    'Service Mesh',
    'Event-driven Architecture',
    'Graph Databases',
    'Relational Databases',
    'Distributed Databases',
    'Machine Learning Operations (MLOps)',
    'Model Deployment',
    'Model Training',
    'Hyperparameter Tuning',
    'Model Evaluation',
    'Data Augmentation',
    'Model Interpretability',
    'Model Explainability',
    'Model Monitoring',
    'Edge AI',
    'AI Ethics',
    'AI Governance',
    'AI Bias Mitigation',
    'AI Fairness',
    'AI Explainability',
    'Computer Graphics',
    'Rendering',
    'Shaders',
    'Texture Mapping',
    'Ray Tracing',
    '3D Animation',
    'Game Engines',
    'Audio Engineering',
    'Sound Design',
    'Music Production',
    'Video Editing',
    'Film Production',
    'Animation Software',
    'VFX Design',
    'VR/AR Development',
    'Robotic Process Automation',
    'RPA Tools',
    'Voice Recognition',
    'Speech Synthesis',
    'Voice Assistant Development',
    'Smart Home Automation',
    'Wearable Technology',
    'Biometrics',
    'Health Tech',
    'EdTech',
    'FinTech',
    'LegalTech',
    'PropTech',
    'GovTech',
    'RetailTech',
    'AgriTech',
    'Cyber-Physical Systems',
    'Smart Cities',
    'Wearable Devices',
    'Sensors',
    'IoT Protocols',
    'Industrial IoT',
    'IoT Cloud Platforms',
    'IoT Security',
    'Edge Computing Devices',
    '5G Technology',
    'Telecommunications',
    'Satellite Communication',
    'Quantum Networks',
    'Smart Grids',
    'Artificial General Intelligence',
    'Human-Computer Interaction',
    'Wearable Computing',
    'Interactive Media',
    'Data-Driven Decision Making',
    'Digital Twins',
    'Predictive Maintenance',
    'Real-time Analytics',
    'Digital Transformation',
    'E-learning Platforms',
    'Online Courses',
    'Learning Management Systems',
    'Video Conferencing',
    'Virtual Classes',
    'Remote Learning',
    'Educational Software',
    'E-books',
    'Instructional Design',
    'Personalized Learning',
    'Learning Analytics',
    'Gamification in Education',
    'Edutainment',
    'Course Development',
    'Online Tutoring',
    'Corporate Training',
    'Onboarding Systems',
    'Employee Training',
    'Talent Development',
    'Leadership Development',
    'Organizational Development',
    'Skill Development',
    'Performance Management',
    'Learning Pathways',
    'Competency Frameworks',
    'HR Tech',
    'Talent Acquisition',
    'Recruiting Tools',
    'Employee Engagement',
    'Workplace Culture',
    'Employee Wellness',
    'HR Analytics',
    'Diversity and Inclusion',
    'Employee Benefits',
    'Payroll Systems',
    'Employee Retention',
    'Workforce Optimization',
    'Employee Satisfaction',
    'Compensation Strategy',
    'Benefits Administration',
    'Workplace Automation',
    'Team Collaboration Tools',
    'Project Collaboration Tools',
    'Remote Work Tools',
    'Video Collaboration Tools',
    'Digital Workflows',
    'Team Communication',
    'Task Management Tools',
    'Virtual Team Building',
    'Employee Feedback Systems',
    'Organizational Tools',
    'Document Management',
    'Cloud Storage Solutions',
    'Virtual Assistant',
    'Virtual Project Management',
    'Human Resource Management',
    'Performance Metrics',
    'Business Intelligence Tools',
    'Customer Service Tools',
    'Customer Experience',
    'Customer Satisfaction',
    'Customer Retention',
    'Customer Loyalty',
    'Customer Support Automation',
    'AI Chatbots for Customer Service',
    'Omnichannel Support',
    'Helpdesk Software',
    'Ticketing Systems',
    'CRM Software',
    'Marketing Automation Tools',
    'Sales Funnel',
    'Lead Generation',
    'Sales Conversion',
    'Account Management',
    'Client Relationship Management',
    'Business Development',
    'B2B Sales',
    'B2C Sales',
    'Sales Training',
    'Inbound Marketing',
    'Outbound Marketing',
    'Event Marketing',
    'Public Relations',
    'Brand Management',
    'Content Marketing',
    'SEO Marketing',
    'Email Campaigns',
    'Affiliate Marketing',
    'Influencer Marketing',
    'Video Marketing',
    'Social Media Marketing',
    'Podcasting',
    'Digital Advertising',
    'Media Buying',
    'Ad Campaign Management',
    'Search Engine Marketing',
    'PPC Campaigns',
    'Display Advertising',
    'Native Advertising',
    'Programmatic Advertising',
    'Remarketing',
    'Google Analytics Certification',
    'Google Ads Certification',
    'Marketing Metrics',
    'Business Analytics',
    'Consumer Behavior Analysis',
    'Market Research',
    'Audience Segmentation',
    'Marketing Strategy',
    'Brand Strategy',
    'Product Marketing',
    'Consumer Insights',
    'Marketing Automation Software',
    'Market Segmentation',
    'Product Positioning',
    'Competitive Analysis',
    'Market Penetration',
    'Value Proposition',
    'Sales Strategy',
    'Market Testing',
    'Pricing Strategy',
    'Distribution Channels',
    'Customer Profiling',
    'Influencer Campaigns',
    'Marketing Budgeting',
    'Digital Advertising Strategy',
    'Salesforce Automation',
    'Sales Metrics',
    'Lead Scoring',
    'Sales Forecasting',
    'Business Analytics Tools',
    'Market Intelligence',
    'Brand Loyalty Programs',
    'Customer Acquisition Strategies',
    'Event Planning',
    'Content Distribution',
    'Public Speaking',
    'Crisis Communication',
    'Media Relations',
    'Strategic Communications',
    'Internal Communications',
    'Corporate Communications',
    'Brand Storytelling',
    'Marketing Channels',
    'PR Campaigns',
    'Social Media Campaigns',
    'Event Management Software',
    'Influencer Outreach',
    'Crisis Management',
    'Cross-channel Marketing',
    'Customer Segmentation',
    'Lead Nurturing',
    'Geotargeting',
    'Customer Profiling',
    'Competitive Intelligence',
    'Brand Awareness',
    'Customer Experience Design',
    'Customer Journey Mapping',
    'Behavioral Marketing',
    'Customer Analytics',
    'Customer Insight Tools',
    'Sales Enablement',
    'Account-based Marketing',
    'Marketing Collateral',
    'Campaign Analytics',
    'Customer Lifecycle Management',
    'Marketing Funnel',
    'Attribution Modeling',
    'Sentiment Analysis for Marketing',
    'Event Analytics',
    'Lead Management',
    'Marketing Attribution',
    'Sales Performance Management',
    'Search Engine Optimization (SEO)',
    'Search Engine Marketing (SEM)',
    'Content Management',
    'Video Content Marketing',
    'E-commerce Marketing',
    'Lead Generation Tools',
    'Sales Tools',
    'Brand Identity',
    'UX Research',
    'Service Design',
    'Digital Strategy',
    'Market Trend Analysis',
    'Consumer Advocacy',
    'Interactive Marketing',
    'Marketing Campaigns',
    'Conversion Rate Optimization',
    'Search Engine Advertising',
    'Landing Page Optimization',
    'Website Analytics',
    'Traffic Analysis',
    'Data-Driven Marketing',
    'Campaign Strategy',
    'Conversion Optimization Tools',
    'Target Market Analysis',
    'Campaign Effectiveness',
    'Content Strategy Frameworks',
    'Customer Service Excellence',
    'B2B Marketing',
    'B2C Marketing',
    'Global Marketing',
    'Inbound Sales',
    'Lead Generation Strategies',
    'Sales Conversion Rate',
    'Sales Lead Management',
    'Sales Process Improvement',
    'Customer Relationship',
    'Sales Analytics',
    'Sales Support',
    'Business Process Automation',
    'Influencer Marketing Strategy',
    'Media Coverage',
    'Brand Positioning',
    'Personal Branding',
    'Corporate Blogging',
    'Public Relations Campaigns',
    'Brand Monitoring',
    'Social Media Engagement',
    'Brand Equity',
    'Online Reputation Management',
    'Brand Recognition',
    'Customer Lifetime Value',
    'Customer Engagement'
  ];


  List<String> skillsList = [
    'Dart', 'Figma', 'Photoshop', 'Python', 'Flutter', 'JavaScript', 'HTML', 'CSS', 'React',
    'Node.js', 'Java', 'SQL', 'Machine Learning', 'Deep Learning', 'Artificial Intelligence',
    'Data Science', 'Excel', 'C++', 'C#', 'Swift', 'Kotlin', 'Ruby', 'PHP', 'Git', 'GitHub',
    'Docker', 'AWS', 'Google Cloud', 'Azure', 'Kubernetes', 'Linux', 'API Development',
    'Rest API', 'GraphQL', 'Unit Testing', 'Selenium', 'Android Development', 'iOS Development',
    'UI/UX Design', 'UX Research', 'Adobe Illustrator', 'Adobe XD', 'InVision', 'UI Prototyping',
    'Sketch', 'WordPress', 'Shopify', 'SEO', 'Content Strategy', 'Digital Marketing', 'Google Analytics',
    'UI Animation', 'Motion Graphics', 'Video Editing', 'Final Cut Pro', 'After Effects', 'Autodesk Maya',
    '3D Modeling', 'Animation', 'Product Management', 'Agile Methodology', 'Scrum', 'Jira', 'Trello',
    'Project Management', 'Time Management', 'Cloud Computing', 'Cybersecurity', 'Penetration Testing',
    'Blockchain', 'Ethereum', 'Solidity', 'Ethereum Smart Contracts', 'NFT', 'FinTech', 'DevOps',
    'CI/CD', 'Virtualization', 'Network Security', 'Software Engineering', 'Web Development',
    'Mobile App Development', 'Game Development', 'Virtual Reality', 'Augmented Reality',
    'Embedded Systems', 'Microservices', 'Distributed Systems', 'API Testing', 'Test Automation',
    'Business Analysis', 'Business Intelligence', 'Data Visualization', 'Tableau', 'Power BI', 'R',
    'SAS', 'SPSS', 'Statistical Analysis', 'Hadoop', 'Spark', 'Big Data', 'NoSQL', 'MongoDB', 'PostgreSQL',
    'MySQL', 'Oracle', 'SQLite', 'Apache Kafka', 'ETL', 'Data Warehousing', 'TensorFlow', 'PyTorch',
    'Keras', 'Scikit-learn', 'OpenCV', 'Computer Vision', 'NLP', 'Natural Language Processing', 'Speech Recognition',
    'Chatbots', 'Voice Assistants', 'Digital Forensics', 'Incident Response', 'SIEM', 'SOC', 'Malware Analysis',
    'Cloud Security', 'Information Security', 'Ethical Hacking', 'Red Teaming', 'Blue Teaming', 'Security Audits',
    'Cryptography', 'Identity Management', 'Penetration Testing', 'Risk Management', 'IT Support',
    'Systems Administration', 'Hardware Engineering', 'Networking', 'Telecommunication', '5G', 'Wi-Fi',
    'Bluetooth', 'IoT', 'Smart Devices', 'Networking Protocols', 'VPN', 'Firewall Configuration', 'Server Setup',
    'Automation', 'Robotic Process Automation', 'SAP', 'ERP', 'Customer Relationship Management', 'Salesforce',
    'Digital Transformation', 'ERP Implementation', 'Business Process Automation', 'Artificial Neural Networks',
    'Reinforcement Learning', 'Mathematics', 'Calculus', 'Linear Algebra', 'Probability', 'Statistics', 'Data Mining',
    'Data Cleansing', 'Business Intelligence Tools', 'Data Structures', 'Algorithms', 'Computational Thinking',
    'Frontend Development', 'Backend Development', 'Full Stack Development', 'Cloud Architecture', 'IT Architecture',
    'Scrum Master', 'Product Owner', 'Agile Coach', 'Team Leadership', 'Software Testing', 'Quality Assurance',
    'Customer Service', 'Technical Support', 'Software Architecture', 'Systems Integration', 'Mobile UI Design',
    'Android UI Design', 'iOS UI Design', 'User Flow Design', 'Wireframing', 'Prototyping', 'User Research',
    'Competitive Analysis', 'Market Research', 'App Store Optimization', 'Content Management', 'Email Marketing',
    'PPC Campaigns', 'Lead Generation', 'Brand Strategy', 'E-commerce', 'Digital Ads', 'Social Media Marketing',
    'Customer Acquisition', 'Brand Design', 'Copywriting', 'Content Creation', 'Video Production', 'Photography',
    'Public Relations', 'Media Relations', 'Event Planning', 'Investor Relations', 'Community Management',
    'Human Resources', 'Recruitment', 'Talent Acquisition', 'Employee Engagement', 'Learning and Development',
    'Performance Management', 'Employee Relations', 'Payroll', 'Labor Laws', 'Workplace Diversity', 'Organizational Design',
    'Leadership Development', 'Business Development', 'Strategic Partnerships', 'Negotiation', 'Sales Management',
    'Sales Strategy', 'Account Management', 'Customer Retention', 'Customer Engagement', 'E-commerce Platforms',
    'Enterprise Solutions', 'Salesforce Development', 'Data Privacy', 'GDPR Compliance', 'Legal Research',
    'Intellectual Property', 'Contract Negotiation', 'Mergers & Acquisitions', 'Corporate Law', 'Startup Legal',
    'Real Estate', 'Patent Law', 'Litigation', 'Tax Law', 'Environmental Law', 'Family Law', 'Legal Writing',
    'Litigation Support', 'Supply Chain Management', 'Logistics', 'Procurement', 'Warehouse Management',
    'Inventory Control', 'Operations Management', 'Production Planning', 'Manufacturing Engineering',
    'Quality Control', 'Lean Manufacturing', 'Six Sigma', 'Kaizen', 'Change Management', 'Operations Research',
    'Human Capital Management', 'Business Strategy', 'Negotiation Skills', 'Financial Modeling', 'Investment Banking',
    'Corporate Finance', 'Private Equity', 'Venture Capital', 'Financial Analysis', 'Risk Analysis', 'Budgeting',
    'Auditing', 'Accounting', 'Taxation', 'Cost Accounting', 'Internal Controls', 'Forensic Accounting',
    'Financial Reporting', 'Insurance', 'Actuarial Science', 'Real Estate Investment', 'Credit Analysis', 'Treasury',
    'Financial Planning', 'Public Accounting', 'Investment Strategies', 'Hedge Funds', 'Real Estate Development',
    'Portfolio Management', 'Personal Finance', 'Asset Management', 'Stock Market', 'Financial Statements',
    'Foreign Exchange', 'Derivatives', 'Blockchain Development', 'Cryptocurrency', 'NFTs', 'Tokenization',
    'Smart Contracts', 'Decentralized Finance', 'Ethereum', 'Bitcoin', 'Litecoin', 'Ripple', 'Chainlink',
    'Blockchain Security', 'Crypto Mining', 'Mining Algorithms', 'Blockchain Solutions',
    'Tokenomics', 'Web3 Development', 'Decentralized Apps', 'Solidity', 'IPFS', 'Polkadot', 'Cardano'
  ];
}
